<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An interactive introduction to statistics for students in the social sciences.">

<title>6&nbsp; Probability – Statistics From Scratch</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-sampling.html" rel="next">
<link href="./05-z-scores.html" rel="prev">
<link href="./resources/icons/favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-7e9717d9caa9b4d114d189eaeb260ada.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b7281a382b19cd07d6f4ffe666e2a619.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-2e7ec11cd726b477cdf9da688c6d099c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-b7281a382b19cd07d6f4ffe666e2a619.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="resources/js/interactive-runtime.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="resources/css/sfs-base.css">
<link rel="stylesheet" href="resources/css/sfs-home.css">
<link rel="stylesheet" href="resources/css/sfs-figures.css">
<link rel="stylesheet" href="resources/css/sfs-tables.css">
<link rel="stylesheet" href="resources/css/sfs-tutorials.css">
<link rel="stylesheet" href="resources/css/sfs-navbar.css">
<link rel="stylesheet" href="resources/css/quiz.css">
<meta property="og:title" content="6&nbsp; Probability – Statistics From Scratch">
<meta property="og:description" content="An interactive introduction to statistics for students in the social sciences.">
<meta property="og:image" content="https://statisticsfromscratch.com/resources/figures/statistics-from-scratch-cover.png">
<meta property="og:site_name" content="Statistics From Scratch">
<meta property="og:image:alt" content="Statistics From Scratch: An Introduction for the Social Sciences, by Rob Brotherton.">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="6&nbsp; Probability – Statistics From Scratch">
<meta name="twitter:description" content="An interactive introduction to statistics for students in the social sciences.">
<meta name="twitter:image" content="https://statisticsfromscratch.com/resources/figures/statistics-from-scratch-cover.png">
<meta name="twitter:image:alt" content="Statistics From Scratch: An Introduction for the Social Sciences, by Rob Brotherton.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
</head>

<body class="nav-sidebar floating nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg border-bottom" data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Statistics From Scratch <span class="sfs-navbar-author">by Rob Brotherton</span></span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability</span></h1>
        </a>     
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Variables &amp; Measurement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-frequency-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Frequency</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-central-tendency.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Central Tendency</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-z-scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><span class="math inline">\(z\)</span>-Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-probability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-statistical-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical Power</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-t-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span>-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-independent-samples-t-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Independent Samples t Test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-related-samples-t-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Related Samples t Test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-related-samples-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Related Samples ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-factorial-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-brief-history-of-probability" id="toc-a-brief-history-of-probability" class="nav-link active" data-scroll-target="#a-brief-history-of-probability">A Brief History of Probability</a>
  <ul class="collapse">
  <li><a href="#catan" id="toc-catan" class="nav-link" data-scroll-target="#catan">Catan</a></li>
  </ul></li>
  <li><a href="#defining-probability" id="toc-defining-probability" class="nav-link" data-scroll-target="#defining-probability">Defining Probability</a>
  <ul class="collapse">
  <li><a href="#rolling-two-dice" id="toc-rolling-two-dice" class="nav-link" data-scroll-target="#rolling-two-dice">Rolling Two Dice</a></li>
  <li><a href="#back-to-catan" id="toc-back-to-catan" class="nav-link" data-scroll-target="#back-to-catan">Back to Catan</a></li>
  </ul></li>
  <li><a href="#counting-marbles" id="toc-counting-marbles" class="nav-link" data-scroll-target="#counting-marbles">Counting marbles</a></li>
  <li><a href="#probability-and-distributions-of-scores" id="toc-probability-and-distributions-of-scores" class="nav-link" data-scroll-target="#probability-and-distributions-of-scores">Probability and Distributions of Scores</a></li>
  <li><a href="#the-normal-distribution" id="toc-the-normal-distribution" class="nav-link" data-scroll-target="#the-normal-distribution">The Normal Distribution</a>
  <ul class="collapse">
  <li><a href="#the-unit-normal-table" id="toc-the-unit-normal-table" class="nav-link" data-scroll-target="#the-unit-normal-table">The Unit Normal Table</a></li>
  <li><a href="#finding-the-area-you-need" id="toc-finding-the-area-you-need" class="nav-link" data-scroll-target="#finding-the-area-you-need">Finding the Area You Need</a></li>
  </ul></li>
  <li><a href="#applying-probability-spider-man" id="toc-applying-probability-spider-man" class="nav-link" data-scroll-target="#applying-probability-spider-man">Applying Probability: Spider-Man</a>
  <ul class="collapse">
  <li><a href="#a-note-on-normality" id="toc-a-note-on-normality" class="nav-link" data-scroll-target="#a-note-on-normality">A Note on Normality</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability</span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<script src="resources/js/d3.min.js"></script>
<script src="resources/js/interactive-figure.js"></script>
<script src="resources/js/catan-board.js"></script>
<script src="resources/js/stat-helpers.js"></script>
<script src="resources/js/critical-table-generator.js"></script>
<script src="resources/js/dice.bundle.js"></script>
<script src="resources/js/distribution-generator.js"></script>
<script src="resources/js/visibility-helper.js"></script>
<script src="resources/js/graph-generator.js"></script>
<div class="interactive-figure-mount" data-interactive-options="{&quot;outcomes&quot;:[3,4],&quot;throwSeed&quot;:144,&quot;shadowMapSize&quot;:1080,&quot;throwSettings&quot;:{&quot;startDistance&quot;:9,&quot;startHeight&quot;:3.8,&quot;forwardSpeed&quot;:15.9,&quot;lift&quot;:0,&quot;lateralSpeed&quot;:0.7,&quot;spread&quot;:1.5},&quot;gravity&quot;:77,&quot;spinStrength&quot;:0.5,&quot;camera&quot;:[-37.4,32,75],&quot;cameraTarget&quot;:[0.1,0.7,-2.6],&quot;fieldOfView&quot;:3}" data-interactive-factory="makeDiceCover" data-interactive-figure="probabilityDiceCover">
<div class="interactive-figure-fallback">
Two oversized dice rolling into view and settling on a three and a four.
</div>
</div>
<p>In the previous chapter, we hinted at thinking probabilistically about extreme scores in a distribution. Here, we’ll go into that idea in more detail. We’ll think about what statisticians mean when they talk about probability and how we go about quantifying it. We’ll need to introduce some new terminology, including probability distributions and independence, and then we’ll return to <span class="math inline">\(z\)</span> scores and see how a normal distribution lets us attach precise probabilities to regions of scores.</p>
<section id="a-brief-history-of-probability" class="level2">
<h2 data-anchor-id="a-brief-history-of-probability">A Brief History of Probability</h2>
<p>People have been thinking about probability for a long time, at least in a broad sense. It’s a useful thing to be able to make predictions about an uncertain future. What are the chances it will rain tomorrow? Can I kill this sabre-toothed tiger, or will it probably kill me first? How much crop should we plant to feed the group? For most of that history, there were no formal ways of articulating <em>how</em> probable something might be. The best people could do was offer rough verbal descriptions, like, “this will happen in most cases.” Aristotle pointed out, for example, that if someone has a fever and you give them honey-water, for the most part they will get better. Sometimes they won’t: it’s not certain, but neither is it entirely unpredictable. It’s something in between, more or less probable.</p>
<p>But <em>how much</em> more or less? The idea of representing uncertainty with numbers and reasoning about it mathematically was a relatively recent development. One of the early inspirations came not from life-and-death decisions but from games of chance. For thousands of years people have been playing games using bits of animal bone — two-sided, coin-like worked and decorated pieces of bone, or astragali, the four-sided ankle bones of sheep and goats. Games played this way were so popular that some people even manufactured astragali out of clay, stone or glass.</p>
<div id="fig-astragal" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-astragal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: A Greek glass astragal, from the 3rd–2nd century BCE. Public domain, via <a href="https://www.metmuseum.org/art/collection/search/249807">Metropolitan Museum of Art, New York</a>.
</figcaption>
<div aria-describedby="fig-astragal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="resources/figures/astragal.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;6.1: A Greek glass astragal, from the 3rd–2nd century BCE. Public domain, via Metropolitan Museum of Art, New York."><img src="resources/figures/astragal.jpg" class="img-fluid figure-img"></a>
</div>
</figure>
</div>
<p>According to the card describing this glass astragal at the Metropolitan Museum of Art in New York, playing with them was so much fun that “knucklebones have been found in tombs where they must have been intended to help the deceased while away endless time.” (So I guess, in a way, it <em>was</em> a matter of life and death.)</p>
<p>Astragali have four faces stable enough to land on, but the faces aren’t the same size or shape, so the four results aren’t equally likely. Eventually cubical dice replaced the irregular animal bones. The example below, something like 4,000 years old, even has the convention of opposite sides adding to seven that modern dice follow. These regularly shaped dice proved appealing to gamblers, and eventually to mathematicians, because it meant they could count outcomes and reason about them in a consistent way.</p>
<div id="fig-old-dice" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-old-dice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Terracotta die, Mohenjo-daro, c.&nbsp;2600–1900 BCE. Ashmolean museum, eamd.25. Photograph by Zunkir, cc by-sa 4.0.
</figcaption>
<div aria-describedby="fig-old-dice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="resources/figures/mohenjodaro-die.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;6.2: Terracotta die, Mohenjo-daro, c.&nbsp;2600–1900 BCE. Ashmolean museum, eamd.25. Photograph by Zunkir, cc by-sa 4.0."><img src="resources/figures/mohenjodaro-die.jpg" class="img-fluid figure-img"></a>
</div>
</figure>
</div>
<section id="catan" class="level3">
<h3 data-anchor-id="catan">Catan</h3>
<p>Let’s think about a slightly more recent game, Catan. It’s a board game played by rolling a pair of dice (not goat knucklebones, thankfully). The board consists of hexagonal terrain tiles, each producing a resource such as wood or grain. Resources are good, so you want to get as many as possible. For now, we’ll ignore the differences between them and the other complications of the game.</p>
<p>Most tiles have a number token. Players place settlements at the corners where tiles meet, and every time the dice are rolled, a settlement gets a resource from each neighboring tile whose number matches the total. So choosing where to settle means choosing which dice totals will pay you for the rest of the game. Suppose you get to go first, and you just want the greatest chance of getting something on each roll. Where would you settle? Why?</p>
<div id="act-catan" class="interactive callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Activity&nbsp;6.1: Place a settlement on a simplified Catan board
</div>
</div>
<div class="callout-body-container callout-body">
<div class="interactive-figure-mount" data-interactive-options="{&quot;mode&quot;:&quot;choose&quot;,&quot;remember&quot;:&quot;sfs-catan-choice&quot;}" data-interactive-factory="makeCatanBoard" data-interactive-figure="catanBoardIntro">
<div class="interactive-figure-fallback">
A simplified Catan board. Settlements go at the corners where numbered tiles meet; a matching dice total makes a tile produce a resource.
</div>
</div>
<div class="callout-footer">
<div class="tutorial-step" data-title="Choose a corner">
<p>Choose a corner on this simplified Catan board to give yourself the best chance of getting resources. For example, the corner at the top-left touching 2, 10, and 6 produces whenever anyone rolls one of those totals. Click a corner to place your settlement. We’ll come back to your choice later. No need to calculate anything yet, just go with your gut. The tokens have little dots below their numbers, and some are red. I wonder why 😉.</p>
</div>
</div>
</div>
</div>
<section class="quiz callout callout-style-default callout-note callout-titled" data-quiz-id="06_probability_catan" aria-label="Commit to a corner"><div class="callout-header d-flex align-content-center"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-caption-container flex-fill"><p>Commit to a corner</p></div></div><div class="callout-body-container callout-body"><article class="quiz-question" data-question-id="catan_settlement"><div class="quiz-prompt"><p>Which corner did you pick, and what made it look good? Name it by the
numbers it touches. Do you think all the dice totals are equally likely?
What would you need to know to compare two corners?</p></div><div class="quiz-control"><textarea placeholder="Write your response" aria-label="Written response"></textarea></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>There is no calculation to get right yet. Record your choice and your
reasoning so you can return to them after working through the dice
example.</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>We are deliberately not settling this yet. Hold on to your choice:
once we have counted the ways two dice can land, we will be able to work
out the probability that any corner on this board pays out, and you can
see how your instinct did.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article></div><script type="application/json" class="quiz-data" data-quiz-id="06_probability_catan">{"title":"Commit to a corner","questions":[{"answer":"There is no calculation to get right yet. Record your choice and your reasoning so you can return to them after working through the dice example.","explanationHtml":"\u003cp\u003eWe are deliberately not settling this yet. Hold on to your choice:\nonce we have counted the ways two dice can land, we will be able to work\nout the probability that any corner on this board pays out, and you can\nsee how your instinct did.\u003c/p\u003e","prompt":"Which corner did you pick, and what made it look good? Name it by the numbers it touches. Do you think all the dice totals are equally likely? What would you need to know to compare two corners?","promptHtml":"\u003cp\u003eWhich corner did you pick, and what made it look good? Name it by the\nnumbers it touches. Do you think all the dice totals are equally likely?\nWhat would you need to know to compare two corners?\u003c/p\u003e","explanation":"We are deliberately not settling this yet. Hold on to your choice: once we have counted the ways two dice can land, we will be able to work out the probability that any corner on this board pays out, and you can see how your instinct did.","type":"free-response","id":"catan_settlement","answerHtml":"\u003cp\u003eThere is no calculation to get right yet. Record your choice and your\nreasoning so you can return to them after working through the dice\nexample.\u003c/p\u003e"}],"id":"06_probability_catan","titleHtml":"\u003cp\u003eCommit to a corner\u003c/p\u003e"}</script></section>
</section>
</section>
<section id="defining-probability" class="level2">
<h2 data-anchor-id="defining-probability">Defining Probability</h2>
<p>Let’s lay out some technical terms now, so that we have the precise language we need to reason about whether you picked the best spot.</p>
<p>First, what exactly do we mean by <em>probability</em>? Generally speaking, a probability model assigns probabilities to events according to a consistent set of rules. What rules? Well, there are distinct traditions and intense disagreement among statisticians and philosophers, which I am happy to sidestep for the most part. The approach that we will take is based in the frequentist tradition. It’s the one that has dominated the social sciences for most of their history, and so it’s the one you ought to understand first.</p>
<p>So a probability, in the frequentist sense, is a number that describes what would happen if we could repeat something many times: the proportion of repetitions in which some event of interest would occur in the long run. Probabilities range from 0 to 1. A probability of .5 means that, in the long run, we would expect the event to occur about half the time.</p>
<p>Let’s think about some simple situations in which there are a small number of equally-likely outcomes that we can count. (Later, we’ll generalize the same ideas to situations where outcomes are not equally likely, and to continuous variables and models where counting individual outcomes no longer works.) We’ll need some terms:</p>
<ul>
<li>An <strong>outcome</strong> is one elementary result of a chance process.</li>
<li>An <strong>event</strong> is the outcome or collection of outcomes we’re actually interested in.</li>
<li>The <strong>sample space</strong> is the set of <em>all</em> the possible outcomes.</li>
</ul>
<p>We use a capital letter <span class="math inline">\(P\)</span> to denote probability and put the event we’re interested in inside parentheses. So <span class="math inline">\(P(A)\)</span> means the probability of Event A. When every outcome in the sample space is equally likely, we can find that probability by counting the outcomes in A and dividing by the total number of possible outcomes.</p>
<p><span class="math display">\[ P(A) = \frac{\text{number of outcomes in } A}{\text{total number of possible outcomes}} \]</span></p>
<p>This should make more sense with some concrete examples. If you flip a coin, there are two possible outcomes, heads or tails. The entire sample space consists of those two outcomes. If we want to denote the probability of heads, we would write <span class="math inline">\(P(\text{heads}) = 1/2 = .5\)</span>. That’s because heads is one of the two equally likely outcomes. (Effectively the event is the outcome; there’s only one outcome that gets you heads.) Likewise, we would write the probability of tails as <span class="math inline">\(P(\text{tails}) = 1/2 = .5\)</span>.</p>
<p>Or we can think about rolling a single fair die. If we’re using a six-sided die, there are six equally likely outcomes in the sample space, the numbers one through six. So the probability of rolling a six is <span class="math inline">\(P(6) = 1/6 \approx .17\)</span>.</p>
<p>Perhaps we’re interested in the event of rolling an even number on a single six-sided die. Now we have an event that can be produced by more than one outcome. There are three individual outcomes (2, 4, 6) that would constitute that event. So the probability of rolling an even number is <span class="math inline">\(P(\text{even}) = 3/6 = 1/2 = .5\)</span>.</p>
<section class="quiz callout callout-style-default callout-note callout-titled" data-quiz-id="06_probability_dice" aria-label="Outcomes, sample spaces, and events"><div class="callout-header d-flex align-content-center"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-caption-container flex-fill"><p>Outcomes, sample spaces, and events</p></div><span class="quiz-progress" aria-label="0 of 3 questions answered" hidden=""><i class="bi bi-check-circle-fill" aria-hidden="true" hidden=""></i><span data-quiz-progress-label="">0 of 3</span></span></div><div class="callout-body-container callout-body"><article class="quiz-question" data-question-id="single_die_sample_space"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">1</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>You roll one fair six-sided die. How many outcomes are in the sample
space?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>6</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>The sample space is the set of all possible elementary results: 1, 2,
3, 4, 5, and 6.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="single_die_event"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">2</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>Still with one die, what is the probability of rolling an even
number?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>0.5</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>“Even” is an event made up of three outcomes — 2, 4, and 6 — out of
six equally likely outcomes, so P(even) = 3 / 6 = .5.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="equally_likely"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">3</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>The rule “probability equals favorable outcomes divided by total
outcomes” works for any situation in which you can list the possible
outcomes.</p></div></div><div class="quiz-control"><fieldset class="quiz-options"><legend class="visually-hidden">Response options</legend><div class="quiz-choice"><input type="radio" name="06_probability_dice-equally_likely" id="06_probability_dice-equally_likely-option-1" value="true" aria-labelledby="06_probability_dice-equally_likely-option-1-text"><div class="quiz-choice-text" id="06_probability_dice-equally_likely-option-1-text"><p>True</p></div></div><div class="quiz-choice"><input type="radio" name="06_probability_dice-equally_likely" id="06_probability_dice-equally_likely-option-2" value="false" aria-labelledby="06_probability_dice-equally_likely-option-2-text"><div class="quiz-choice-text" id="06_probability_dice-equally_likely-option-2-text"><p>False</p></div></div></fieldset></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>False</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>It only works when those outcomes are equally likely. There are two
possible outcomes to tomorrow’s weather in the sense that it either
rains or it doesn’t, but that does not make the probability of rain
.5.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article></div><script type="application/json" class="quiz-data" data-quiz-id="06_probability_dice">{"title":"Outcomes, sample spaces, and events","questions":[{"answer":"6","tolerance":"0","prompt":"You roll one fair six-sided die. How many outcomes are in the sample space?","promptHtml":"\u003cp\u003eYou roll one fair six-sided die. How many outcomes are in the sample\nspace?\u003c/p\u003e","explanationHtml":"\u003cp\u003eThe sample space is the set of all possible elementary results: 1, 2,\n3, 4, 5, and 6.\u003c/p\u003e","explanation":"The sample space is the set of all possible elementary results: 1, 2, 3, 4, 5, and 6.","type":"numeric","id":"single_die_sample_space","answerHtml":"\u003cp\u003e6\u003c/p\u003e"},{"answer":"0.5","tolerance":"1.0e-3","prompt":"Still with one die, what is the probability of rolling an even number?","promptHtml":"\u003cp\u003eStill with one die, what is the probability of rolling an even\nnumber?\u003c/p\u003e","explanationHtml":"\u003cp\u003e“Even” is an event made up of three outcomes — 2, 4, and 6 — out of\nsix equally likely outcomes, so P(even) = 3 / 6 = .5.\u003c/p\u003e","explanation":"“Even” is an event made up of three outcomes — 2, 4, and 6 — out of six equally likely outcomes, so P(even) = 3 / 6 = .5.","type":"numeric","id":"single_die_event","answerHtml":"\u003cp\u003e0.5\u003c/p\u003e"},{"answer":false,"explanationHtml":"\u003cp\u003eIt only works when those outcomes are equally likely. There are two\npossible outcomes to tomorrow’s weather in the sense that it either\nrains or it doesn’t, but that does not make the probability of rain\n.5.\u003c/p\u003e","prompt":"The rule “probability equals favorable outcomes divided by total outcomes” works for any situation in which you can list the possible outcomes.","promptHtml":"\u003cp\u003eThe rule “probability equals favorable outcomes divided by total\noutcomes” works for any situation in which you can list the possible\noutcomes.\u003c/p\u003e","explanation":"It only works when those outcomes are equally likely. There are two possible outcomes to tomorrow’s weather in the sense that it either rains or it doesn’t, but that does not make the probability of rain .5.","type":"true-false","id":"equally_likely","answerHtml":""}],"id":"06_probability_dice","titleHtml":"\u003cp\u003eOutcomes, sample spaces, and events\u003c/p\u003e"}</script></section>
<section id="rolling-two-dice" class="level3">
<h3 data-anchor-id="rolling-two-dice">Rolling Two Dice</h3>
<p>The same logic applies to rolling multiple dice; the sample space just expands, and we have to be careful about how to count things. Something that tripped up some early gamblers is that we’re interested in the sum of the dice, but some sums can be arrived at in multiple ways.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Did you notice the red and blue dice at the top of the chapter? Red landed on 3 and blue landed on 4, for a sum of 7. But what if red had instead landed on 4 and blue on 3? The total would have been 7 as well. We need to count all the different ways each die might land to give the various possible totals. Assuming the dice are fair, each of the six red results can be paired with each of the six blue results, giving <span class="math inline">\(6 \times 6 = 36\)</span> equally likely outcomes. <a href="#tbl-dice-sums" class="quarto-xref">Table&nbsp;<span>6.1</span></a> shows them all: rows give the red die’s result; columns give the blue die’s result.</p>
<div id="tbl-dice-sums" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dice-sums-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: The totals associated with all 36 ordered outcomes of rolling two dice.
</figcaption>
<div aria-describedby="tbl-dice-sums-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;"><strong>1</strong></th>
<th style="text-align: center;"><strong>2</strong></th>
<th style="text-align: center;"><strong>3</strong></th>
<th style="text-align: center;"><strong>4</strong></th>
<th style="text-align: center;"><strong>5</strong></th>
<th style="text-align: center;"><strong>6</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>4</strong></td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>5</strong></td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>6</strong></td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">12</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
<p>We can take the 36 sums in the table and draw a bar graph counting how often each value appears, like we did in Chapter 2. Each bar in <a href="#fig-dice-sums-counts" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> counts the entries in the table that give that total. A total of 2 appears once, while 7 appears six times.</p>
<div id="fig-dice-sums-counts" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dice-sums-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Counts of the dice totals in the table of 36 possible outcomes.
</figcaption>
<div aria-describedby="fig-dice-sums-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="interactive-figure-mount" data-interactive-options="{&quot;type&quot;:&quot;bar&quot;,&quot;scale&quot;:&quot;frequency&quot;,&quot;data&quot;:[2,3,4,5,6,7,3,4,5,6,7,8,4,5,6,7,8,9,5,6,7,8,9,10,6,7,8,9,10,11,7,8,9,10,11,12],&quot;aspectRatio&quot;:2,&quot;labels&quot;:{&quot;x&quot;:&quot;Sum of two dice&quot;,&quot;y&quot;:&quot;Number of outcomes&quot;},&quot;ariaLabel&quot;:&quot;Bar graph of counts among 36 possible ordered dice outcomes. Totals 2 through 12 have counts 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, and 1.&quot;}" data-interactive-factory="makeGraph" data-interactive-figure="diceSumsCounts">
<div class="interactive-figure-fallback">
Bar graph of counts among 36 possible ordered dice outcomes. Totals 2 through 12 have counts 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, and 1.
</div>
</div>
</div>
</figure>
</div>
<p>Now let’s make a similar version of the graph, with a small mathematical change:</p>
<div id="fig-dice-sums-bar-graph" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dice-sums-bar-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: The same dice totals, with each count divided by 36 to give a probability.
</figcaption>
<div aria-describedby="fig-dice-sums-bar-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="interactive-figure-mount" data-interactive-options="{&quot;type&quot;:&quot;bar&quot;,&quot;scale&quot;:&quot;proportion&quot;,&quot;data&quot;:[2,3,4,5,6,7,3,4,5,6,7,8,4,5,6,7,8,9,5,6,7,8,9,10,6,7,8,9,10,11,7,8,9,10,11,12],&quot;aspectRatio&quot;:2,&quot;labels&quot;:{&quot;x&quot;:&quot;Sum of two dice&quot;,&quot;y&quot;:&quot;Probability&quot;},&quot;ariaLabel&quot;:&quot;Bar graph showing probabilities for the sum of two dice, rising from 1/36 for 2 to 6/36 for 7, then falling symmetrically to 1/36 for 12.&quot;}" data-interactive-factory="makeGraph" data-interactive-figure="diceSumsBarGraph">
<div class="interactive-figure-fallback">
Bar graph showing probabilities for the sum of two dice, rising from 1/36 for 2 to 6/36 for 7, then falling symmetrically to 1/36 for 12.
</div>
</div>
</div>
</figure>
</div>
<p>Did you notice the change? We divided each count by the total, 36, to turn frequencies into proportions. The distribution looks the same; the bars have the same relative heights. Only the vertical scale changes.</p>
<p>Its a small mathematical tweak but a bigger conceptual leap. Rather than counting every outcome in the sample space once, as in <a href="#fig-dice-sums-counts" class="quarto-xref">Figure&nbsp;<span>6.3</span></a>, each proportion tells us the probability of a total on a roll we <em>haven’t made yet</em>. These probabilities form a <strong>probability distribution</strong>. It shows every possible value of the variable and the probability attached to each one. The original counts add up to 36; the probabilities add up to 1.</p>
<p>We can use it to predict frequencies: over 360 rolls, for example, we’d expect a total of 7 about <span class="math inline">\(360 \times (6/36)=60\)</span> times. If we <em>actually</em> roll the dice 360 times we might not get exactly 60 sevens, but We haven’t counted any actual sevens to reach that conclusion. And we aren’t promising exactly 60; we’re describing what to expect from the chance process.</p>
<p>One more thing to note. If two events cannot happen on the same trial, they are <strong>mutually exclusive</strong>, and we can add their probabilities to find the probability of one <em>or</em> the other. For example, the probability of rolling a 5 or a 6 is:</p>
<p><span class="math display">\[ P(5 \text{ or } 6) = P(5) + P(6) = \frac{4}{36} + \frac{5}{36} = \frac{9}{36} \approx .25 \]</span></p>
<section class="quiz callout callout-style-default callout-note callout-titled" data-quiz-id="06_probability_pair_of_dice" aria-label="Counting with two dice"><div class="callout-header d-flex align-content-center"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-caption-container flex-fill"><p>Counting with two dice</p></div><span class="quiz-progress" aria-label="0 of 3 questions answered" hidden=""><i class="bi bi-check-circle-fill" aria-hidden="true" hidden=""></i><span data-quiz-progress-label="">0 of 3</span></span></div><div class="callout-body-container callout-body"><article class="quiz-question" data-question-id="sum_nine"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">1</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>Using the table of 36 outcomes, what is the probability of rolling a
sum of 9 with two fair dice?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""><div class="quiz-hint" data-quiz-hint-index="1" hidden=""><strong>Hint</strong><p>Count the cells containing a 9. Remember that a 4 on the first die
and a 5 on the second is a different outcome from a 5 on the first die
and a 4 on the second.</p></div></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>0.1111</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>There are four ways to make a 9 — (3,6), (4,5), (5,4), and (6,3) —
out of 36 equally likely outcomes, so P(9) = 4 / 36 = .11.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="sums_eleven_outcomes"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">2</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>There are 11 possible sums (2 through 12) but 36 outcomes in the
sample space. How many outcomes produce a sum of 7?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>6</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>Six: (1,6), (2,5), (3,4), (4,3), (5,2), and (6,1). The 11 sums are
not equally likely precisely because different numbers of outcomes
produce them, which is why we count outcomes rather than sums.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="corner_three_eight_ten"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">3</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>Over on the right of the board, one corner touches tiles numbered 3,
8, and 10. What is the probability that it produces something on a given
roll — that is, the probability of rolling a 3, an 8, or a 10?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""><div class="quiz-hint" data-quiz-hint-index="1" hidden=""><strong>Hint</strong><p>A single roll cannot be two different sums at once, so no outcome
gets counted twice. Add up the ways.</p></div></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>0.2778</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>There are two ways to roll a 3, five ways to roll an 8, and three
ways to roll a 10, and no outcome is more than one of them, so P(3 or 8
or 10) = (2 + 5 + 3) / 36 = 10 / 36 = .28.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article></div><script type="application/json" class="quiz-data" data-quiz-id="06_probability_pair_of_dice">{"title":"Counting with two dice","questions":[{"answer":"0.1111","tolerance":"5.0e-3","prompt":"Using the table of 36 outcomes, what is the probability of rolling a sum of 9 with two fair dice?","promptHtml":"\u003cp\u003eUsing the table of 36 outcomes, what is the probability of rolling a\nsum of 9 with two fair dice?\u003c/p\u003e","hints":[{"text":"Count the cells containing a 9. Remember that a 4 on the first die and a 5 on the second is a different outcome from a 5 on the first die and a 4 on the second.","textHtml":"\u003cp\u003eCount the cells containing a 9. Remember that a 4 on the first die\nand a 5 on the second is a different outcome from a 5 on the first die\nand a 4 on the second.\u003c/p\u003e"}],"explanationHtml":"\u003cp\u003eThere are four ways to make a 9 — (3,6), (4,5), (5,4), and (6,3) —\nout of 36 equally likely outcomes, so P(9) = 4 / 36 = .11.\u003c/p\u003e","explanation":"There are four ways to make a 9 — (3,6), (4,5), (5,4), and (6,3) — out of 36 equally likely outcomes, so P(9) = 4 / 36 = .11.","type":"numeric","id":"sum_nine","answerHtml":"\u003cp\u003e0.1111\u003c/p\u003e"},{"answer":"6","tolerance":"0","prompt":"There are 11 possible sums (2 through 12) but 36 outcomes in the sample space. How many outcomes produce a sum of 7?","promptHtml":"\u003cp\u003eThere are 11 possible sums (2 through 12) but 36 outcomes in the\nsample space. How many outcomes produce a sum of 7?\u003c/p\u003e","explanationHtml":"\u003cp\u003eSix: (1,6), (2,5), (3,4), (4,3), (5,2), and (6,1). The 11 sums are\nnot equally likely precisely because different numbers of outcomes\nproduce them, which is why we count outcomes rather than sums.\u003c/p\u003e","explanation":"Six: (1,6), (2,5), (3,4), (4,3), (5,2), and (6,1). The 11 sums are not equally likely precisely because different numbers of outcomes produce them, which is why we count outcomes rather than sums.","type":"numeric","id":"sums_eleven_outcomes","answerHtml":"\u003cp\u003e6\u003c/p\u003e"},{"answer":"0.2778","tolerance":"5.0e-3","prompt":"Over on the right of the board, one corner touches tiles numbered 3, 8, and 10. What is the probability that it produces something on a given roll — that is, the probability of rolling a 3, an 8, or a 10?","promptHtml":"\u003cp\u003eOver on the right of the board, one corner touches tiles numbered 3,\n8, and 10. What is the probability that it produces something on a given\nroll — that is, the probability of rolling a 3, an 8, or a 10?\u003c/p\u003e","hints":[{"text":"A single roll cannot be two different sums at once, so no outcome gets counted twice. Add up the ways.","textHtml":"\u003cp\u003eA single roll cannot be two different sums at once, so no outcome\ngets counted twice. Add up the ways.\u003c/p\u003e"}],"explanationHtml":"\u003cp\u003eThere are two ways to roll a 3, five ways to roll an 8, and three\nways to roll a 10, and no outcome is more than one of them, so P(3 or 8\nor 10) = (2 + 5 + 3) / 36 = 10 / 36 = .28.\u003c/p\u003e","explanation":"There are two ways to roll a 3, five ways to roll an 8, and three ways to roll a 10, and no outcome is more than one of them, so P(3 or 8 or 10) = (2 + 5 + 3) / 36 = 10 / 36 = .28.","type":"numeric","id":"corner_three_eight_ten","answerHtml":"\u003cp\u003e0.2778\u003c/p\u003e"}],"id":"06_probability_pair_of_dice","titleHtml":"\u003cp\u003eCounting with two dice\u003c/p\u003e"}</script></section>
</section>
<section id="back-to-catan" class="level3">
<h3 data-anchor-id="back-to-catan">Back to Catan</h3>
<p>Now we can return to your settlement in Catan. Armed with the tools and terms we just outlined, are you still pleased with your choice?</p>
<div id="fig-catan-verdict" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-catan-verdict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: The Catan board, now shaded by the probability that each corner earns at least one resource on a roll: bigger, greener corners have higher probabilities. If you chose a corner earlier, it is circled, and the board’s best corner is marked.
</figcaption>
<div aria-describedby="fig-catan-verdict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="interactive-figure-mount" data-interactive-options="{&quot;mode&quot;:&quot;rated&quot;,&quot;rating&quot;:&quot;theory&quot;,&quot;showReadout&quot;:false,&quot;remember&quot;:&quot;sfs-catan-choice&quot;,&quot;highlight&quot;:[&quot;reader&quot;,&quot;best-chance&quot;]}" data-interactive-factory="makeCatanBoard" data-interactive-figure="catanBoardVerdict">
<div class="interactive-figure-fallback">
The Catan board with corners rated by their probability of producing at least one resource. The best corner touches 5, 6, and 9, with probability 13/36.
</div>
</div>
</div>
</figure>
</div>
<p>The best corner on this board is where the 5, the 6 and the 9 meet, up near the top. It pays out if the total is <em>any one</em> of those numbers. Since those events are mutually exclusive, we can add:</p>
<p><span class="math display">\[ P(5 \text{ or } 6 \text{ or } 9) = \frac{4 + 5 + 4}{36} = \frac{13}{36} \approx .36 \]</span></p>
<p>Nothing else on this board gets past <span class="math inline">\(10/36\)</span>, or about .28. The board had some clues: the red numbers, the 6s and 8s, are individually the most likely totals (since there’s no 7 on this board; in the real game something else happens when 7 is rolled). But a settlement’s probability depends on <em>all</em> the different totals that pay it. The little dots on the tokens were another clue: they count how many of the 36 outcomes produce that total.</p>
<p>Of course, just picking the best spot in a statistical sense won’t win you the game. Like we pointed out already, the mathematical expected frequency of <span class="math inline">\(.36\)</span> does not guarantee that those three numbers will occur on eaxactly 36 out of 100 real rolls. In a single game of Catan, any given corner might pay out more or less than expected.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> But at least now you can reason about your choice in a precise way.</p>
</section>
</section>
<section id="counting-marbles" class="level2">
<h2 data-anchor-id="counting-marbles">Counting marbles</h2>
<p>Okay, rolling dice is fun, but every statistics textbook I’ve ever read has used the idea of picking marbles out of a jar to illustrate ideas of probability, so it would be remiss of me not to.</p>
<p>Actually, the idea has a long and distinguished pedigree. In <em>The Art of Conjecturing</em>, published in 1713, Jacob Bernoulli asked his reader to imagine an urn containing 5,000 pebbles, in some unknown ratio of white to black. By drawing pebbles repeatedly, someone who couldn’t see the contents could estimate that ratio from the proportion of white pebbles they observed <span class="citation" data-cites="bernoulli2006conjecturing">(<a href="references.html#ref-bernoulli2006conjecturing" role="doc-biblioref">Bernoulli, 2006</a>)</span>.</p>
<p>That observed proportion is an <strong>observed relative frequency</strong>. Over many independent repetitions of the same chance process, it tends toward the underlying probability: the <strong>law of large numbers</strong>. This connects the probability we can calculate from known contents with something we can estimate when the contents are hidden. But keeping the chance process the same matters. A small procedural detail, putting the pebble back, turns out to make a difference.</p>
<p>A jar contains 10 white marbles and 40 blue marbles. If each marble is equally likely to be drawn, <span class="math inline">\(P(\text{white})=10/50=.2\)</span>. Now suppose we draw a white marble. Does the next draw still have a .2 probability of being white?</p>
<p>That depends on what we do with the first marble. If we <strong>sample with replacement</strong>, we put it back and mix the jar before drawing again. There are still 10 white marbles among 50, so the probability stays .2. The draws are <strong>independent</strong>: knowing the first result doesn’t change the probabilities for the second.</p>
<p>If we <strong>sample without replacement</strong>, we leave the first marble out. After drawing white, only 9 white marbles and 49 marbles in total remain. The probability of another white is now <span class="math inline">\(9/49 \approx .184\)</span>. The draws are dependent, because knowing the first result changes the probabilities for the second. We can express that with <strong>conditional probability</strong> notation:</p>
<p><span class="math display">\[P(\text{second white}\mid\text{first white})=\frac{9}{49}.\]</span></p>
<p>The vertical bar means “given that”: the probability of a second white marble <em>given that</em> the first was white. With replacement, that conditional probability would simply be .2.</p>
<section class="quiz callout callout-style-default callout-note callout-titled" data-quiz-id="06_probability_marbles" aria-label="Does the First Draw Change the Second?"><div class="callout-header d-flex align-content-center"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-caption-container flex-fill"><p>Does the First Draw Change the Second?</p></div><span class="quiz-progress" aria-label="0 of 2 questions answered" hidden=""><i class="bi bi-check-circle-fill" aria-hidden="true" hidden=""></i><span data-quiz-progress-label="">0 of 2</span></span></div><div class="callout-body-container callout-body"><article class="quiz-question" data-question-id="second_white"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">1</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>A jar has 10 white marbles and 40 blue marbles. You draw one white
marble and do not replace it. What is the probability that the second
marble is white?</p></div></div><div class="quiz-control"><textarea placeholder="Write your response" aria-label="Written response"></textarea></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>The probability is 9/49, or about .18, because one white marble has
been removed and 49 marbles remain.</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>Without replacement, the second draw depends on the first. In
symbols, <span class="math inline">\(P(\text{second white} \mid
\text{first white}) = 9/49\)</span>.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="replacement"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">2</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>If you replace the first marble and mix the jar, drawing white first
makes blue more likely on the next draw.</p></div></div><div class="quiz-control"><fieldset class="quiz-options"><legend class="visually-hidden">Response options</legend><div class="quiz-choice"><input type="radio" name="06_probability_marbles-replacement" id="06_probability_marbles-replacement-option-1" value="true" aria-labelledby="06_probability_marbles-replacement-option-1-text"><div class="quiz-choice-text" id="06_probability_marbles-replacement-option-1-text"><p>True</p></div></div><div class="quiz-choice"><input type="radio" name="06_probability_marbles-replacement" id="06_probability_marbles-replacement-option-2" value="false" aria-labelledby="06_probability_marbles-replacement-option-2-text"><div class="quiz-choice-text" id="06_probability_marbles-replacement-option-2-text"><p>False</p></div></div></fieldset></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>False</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>Replacement restores the same 10 white and 40 blue marbles. The next
draw is independent of the first: white still has probability .2 and
blue .8.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article></div><script type="application/json" class="quiz-data" data-quiz-id="06_probability_marbles">{"title":"Does the First Draw Change the Second?","questions":[{"answer":"The probability is 9/49, or about .18, because one white marble has been removed and 49 marbles remain.","explanationHtml":"\u003cp\u003eWithout replacement, the second draw depends on the first. In\nsymbols, \u003cspan class=\"math inline\"\u003e\\(P(\\text{second white} \\mid\n\\text{first white}) = 9/49\\)\u003c/span\u003e.\u003c/p\u003e","prompt":"A jar has 10 white marbles and 40 blue marbles. You draw one white marble and do not replace it. What is the probability that the second marble is white?","promptHtml":"\u003cp\u003eA jar has 10 white marbles and 40 blue marbles. You draw one white\nmarble and do not replace it. What is the probability that the second\nmarble is white?\u003c/p\u003e","explanation":"Without replacement, the second draw depends on the first. In symbols, P(\\text{second white} \\mid \\text{first white}) = 9/49.","type":"free-response","id":"second_white","answerHtml":"\u003cp\u003eThe probability is 9/49, or about .18, because one white marble has\nbeen removed and 49 marbles remain.\u003c/p\u003e"},{"answer":false,"explanationHtml":"\u003cp\u003eReplacement restores the same 10 white and 40 blue marbles. The next\ndraw is independent of the first: white still has probability .2 and\nblue .8.\u003c/p\u003e","prompt":"If you replace the first marble and mix the jar, drawing white first makes blue more likely on the next draw.","promptHtml":"\u003cp\u003eIf you replace the first marble and mix the jar, drawing white first\nmakes blue more likely on the next draw.\u003c/p\u003e","explanation":"Replacement restores the same 10 white and 40 blue marbles. The next draw is independent of the first: white still has probability .2 and blue .8.","type":"true-false","id":"replacement","answerHtml":""}],"id":"06_probability_marbles","titleHtml":"\u003cp\u003eDoes the First Draw Change the Second?\u003c/p\u003e"}</script></section>
<p>In social science, independence has the same meaning: knowing one person’s score doesn’t change the probabilities for another’s. That can fail if, for example, people discuss their answers before responding, or if observations come from members of the same household who share relevant influences. One person needn’t directly cause another’s response for their scores to be related.</p>
<p>A <strong>random sample</strong> is selected by a chance procedure. Random selection and independence are different ideas: both marble procedures use chance, but only replacing and mixing the marble makes successive draws independent. In the next chapter, we’ll see why independence matters when combining observations into a sample mean, and how this idealization applies when we sample people.</p>
</section>
<section id="probability-and-distributions-of-scores" class="level2">
<h2 data-anchor-id="probability-and-distributions-of-scores">Probability and Distributions of Scores</h2>
<p>The same logic applies to the scores we study in social science. We can ask for the probability of randomly selecting a score equal to a value, above a value, or within a range.</p>
<p>Take this little distribution of ten scores.</p>
<div class="interactive-figure-mount" data-interactive-options="{&quot;type&quot;:&quot;block&quot;,&quot;data&quot;:[1,1,1,1,2,2,2,4,4,5],&quot;xDomain&quot;:[0,6],&quot;xTickValues&quot;:[1,2,3,4,5],&quot;labels&quot;:{&quot;x&quot;:&quot;Scores&quot;,&quot;y&quot;:&quot;Frequency&quot;}}" data-interactive-factory="makeGraph" data-interactive-figure="probabilityBlocksDemo">
<div class="interactive-figure-fallback">
Block histogram of ten scores: four 1s, three 2s, two 4s, and one 5.
</div>
</div>
<p>If we select one score at random, each of the ten blocks is one equally likely outcome. Let <span class="math inline">\(X\)</span> stand for the value of the score we select. Four of the ten blocks have a value of 1, so:</p>
<p><span class="math display">\[ P(X = 1) = \frac{4}{10} = .4 \]</span></p>
<p>There are no blocks at 3, so <span class="math inline">\(P(X=3)=0\)</span>. And we can define events that collect several values at once:</p>
<p><span class="math display">\[ P(X \ge 4) = \frac{3}{10} = .3 \]</span></p>
<p><span class="math display">\[ P(1 &lt; X &lt; 5) = \frac{5}{10} = .5 \]</span></p>
<p>This is the same move we made with the dice: divide each frequency by the total to get a probability distribution. There we divided by 36; here we divide by ten. The block histogram describes scores we’ve already observed, but those proportions also tell us what to expect when we randomly select one of the blocks. For example, <span class="math inline">\(P(X=1)=.4\)</span> predicts that about 40% of repeated selections, with replacement, would give a score of 1. Once again, we’re using a distribution to reason about selections we haven’t made yet.</p>
</section>
<section id="the-normal-distribution" class="level2">
<h2 data-anchor-id="the-normal-distribution">The Normal Distribution</h2>
<p>What if we’re interested in a continuous variable, such as height or reaction time, rather than a little collection of scores we can count? Remember the smooth curves in <a href="./02-frequency-distributions.html#smooth-curves">Chapter 2</a>. They represented models of how scores were distributed, including scores we hadn’t actually observed. We also met one particular model, the symmetric, bell-shaped <strong>normal distribution</strong>. Now we can put that curve to work calculating probabilities.</p>
<p>French mathematician Abraham de Moivre discovered the normal curve while thinking about the long-run probabilities of simple events with two equally-likely outcomes, like a coin toss. Like we saw earlier, for a fair coin, each outcome (heads or tails) has a probability of <span class="math inline">\(.5\)</span>. But what happens when you toss a coin a bunch of times, say 3,600? Will you get precisely half—1,800—come up heads? Probably not. Toss the coin another 3,600 times and you’ll get a different answer again. If you had the time to do this again and again, the answers would usually be somewhere close to the expected 1,800; rarely will it be far away. De Moivre realized that we can approximate the distribution that all these outcomes would follow with a simple smooth curve—the bell-shaped curve that we now call the normal distribution.</p>
<p>The normal curve is defined by a mathematical equation:</p>
<p><span id="eq-normal-distribution"><span class="math display">\[Y = \frac{1}{\sqrt{2 \pi \sigma^2}} e^{-\frac{(X-\mu)^2}{2\sigma^2}} \tag{6.1}\]</span></span></p>
<p>Now, you don’t really have to know this equation for the work we’re going to do throughout this book, so if it makes you sweat just looking at it, don’t worry. But it is worth looking at briefly to get a sense of how it’s constructed. It has an <span class="math inline">\((x-\mu)^2\)</span> in there, which should look familiar from our chapter on variability, and <span class="math inline">\(\sigma\)</span> is part of this too, so variability has something important to do with the shape. The value <span class="math inline">\(Y\)</span> gives the height of the curve (its <em>density</em>) at a particular value of <span class="math inline">\(X\)</span>. But again, don’t worry about remembering the specifics. Just know that the equation defines the curve precisely.</p>
<p>Here is the connection to probability. With the dice, dividing by 36 gave us probabilities whose total was 1. For a continuous model, we scale the curve so that its <em>total area</em> is 1. The area between two scores then gives the probability of a randomly selected score falling in that interval. If a population can be reasonably modelled by a normal distribution, we can calculate those probabilities without recording and counting every individual score.</p>
<p>This is why we called the height <strong>density</strong> back in Chapter 2. A high part of the curve means scores are concentrated around that value; the height itself isn’t a probability. To get a probability, we need a region with some width: the area under the curve across the interval we’re interested in. An exact point has no width and therefore no area, so under a continuous model <span class="math inline">\(P(X=x)=0\)</span>. Our recorded measurements are rounded, and a recorded value represents a small interval. Including or excluding a single exact endpoint doesn’t change a continuous-model probability: <span class="math inline">\(P(X&lt;a)=P(X\le a)\)</span>.</p>
<p>A normal distribution is completely specified by its mean and standard deviation. Those can be whatever, but it is often easiest to work with the <strong>standard normal distribution</strong>, also called the <strong>unit normal distribution</strong>. This is a normal distribution with a mean of 0 and a standard deviation of 1. Sound familiar? The <span class="math inline">\(z\)</span> scores we learned to calculate in the previous chapter put scores onto that standard scale:</p>
<p><span class="math display">\[z=\frac{X-\mu}{\sigma}.\]</span></p>
<p>If <span class="math inline">\(X\)</span> follows a normal distribution, its standardized scores follow the standard normal distribution. Standardizing changes the units, but preserves the proportion of scores in each corresponding region. It does not turn a nonnormal distribution into a normal one. We use capital <span class="math inline">\(Z\)</span> for the standardized variable and lowercase <span class="math inline">\(z\)</span> for a particular value.</p>
<p>The total area under the curve is 1. The proportion of that area in a region is the probability of a randomly selected score falling in that region, according to the model. So, for example, 34.13% of the area of the curve lies between the mean and one standard deviation above the mean. And because it’s symmetrical, the same 34.13% lies between the mean and one standard deviation below the mean. Another 13.59% lies between one and two standard deviations from the mean on each side. And 2.28% lies more than two standard deviations above the mean, with another 2.28% more than two standard deviations below it. Together, the two extreme regions contain about 4.56% of the distribution.</p>
<div class="interactive-figure-mount" data-interactive-options="{   &quot;distribution&quot;: &quot;normal&quot;,   &quot;xDomain&quot;: [-4, 4],   &quot;xTicks&quot;: 9,   &quot;style&quot;: &quot;minimal&quot;,   &quot;xAxis&quot;: true,   &quot;yLabel&quot;: false,   &quot;labels&quot;: {&quot;x&quot;: &quot;z-score&quot;},   &quot;markers&quot;: [     {&quot;at&quot;: -2, &quot;label&quot;: false, &quot;color&quot;: &quot;var(--graph-axis-color, #7b818a)&quot;, &quot;dash&quot;: &quot;3 4&quot;, &quot;strokeWidth&quot;: 1.2},     {&quot;at&quot;: -1, &quot;label&quot;: false, &quot;color&quot;: &quot;var(--graph-axis-color, #7b818a)&quot;, &quot;dash&quot;: &quot;3 4&quot;, &quot;strokeWidth&quot;: 1.2},     {&quot;at&quot;: 0, &quot;label&quot;: false, &quot;color&quot;: &quot;var(--graph-axis-color, #7b818a)&quot;, &quot;dash&quot;: &quot;3 4&quot;, &quot;strokeWidth&quot;: 1.2},     {&quot;at&quot;: 1, &quot;label&quot;: false, &quot;color&quot;: &quot;var(--graph-axis-color, #7b818a)&quot;, &quot;dash&quot;: &quot;3 4&quot;, &quot;strokeWidth&quot;: 1.2},     {&quot;at&quot;: 2, &quot;label&quot;: false, &quot;color&quot;: &quot;var(--graph-axis-color, #7b818a)&quot;, &quot;dash&quot;: &quot;3 4&quot;, &quot;strokeWidth&quot;: 1.2}   ],   &quot;shade&quot;: [     {&quot;to&quot;: -2, &quot;label&quot;: &quot;percent&quot;, &quot;color&quot;: &quot;var(--sfs-accent, #2c7fb8)&quot;, &quot;opacity&quot;: 0.12},     {&quot;between&quot;: [-2, -1], &quot;label&quot;: &quot;percent&quot;, &quot;color&quot;: &quot;var(--sfs-accent, #2c7fb8)&quot;, &quot;opacity&quot;: 0.22},     {&quot;between&quot;: [-1, 0], &quot;label&quot;: &quot;percent&quot;, &quot;color&quot;: &quot;var(--sfs-accent, #2c7fb8)&quot;, &quot;opacity&quot;: 0.38},     {&quot;between&quot;: [0, 1], &quot;label&quot;: &quot;percent&quot;, &quot;color&quot;: &quot;var(--sfs-accent, #2c7fb8)&quot;, &quot;opacity&quot;: 0.38},     {&quot;between&quot;: [1, 2], &quot;label&quot;: &quot;percent&quot;, &quot;color&quot;: &quot;var(--sfs-accent, #2c7fb8)&quot;, &quot;opacity&quot;: 0.22},     {&quot;from&quot;: 2, &quot;label&quot;: &quot;percent&quot;, &quot;color&quot;: &quot;var(--sfs-accent, #2c7fb8)&quot;, &quot;opacity&quot;: 0.12}   ],   &quot;animate&quot;: true }" data-interactive-factory="makeDistributionGraph" data-interactive-figure="zRegionsLabelled">
<div class="interactive-figure-fallback">
Standard normal curve divided at z = -2, -1, 0, 1, and 2, with each region labeled by the percentage of the distribution it contains: 2.28%, 13.59%, 34.13%, 34.13%, 13.59%, and 2.28%.
</div>
</div>
<section id="the-unit-normal-table" class="level3">
<h3 data-anchor-id="the-unit-normal-table">The Unit Normal Table</h3>
<p>Of course, we aren’t limited to those particular regions. We can take any <span class="math inline">\(z\)</span> score and determine the probability of a score falling above or below that value under a standard normal model. In the olden days, you would look up something called a <span class="math inline">\(z\)</span> table, a standard normal table, or a unit normal table. These tables vary in how they’re arranged. The one below lists nonnegative <span class="math inline">\(z\)</span> scores along with the areas to their left, to their right, and between the mean and the score. (Computers have made these tables largely obsolete, but it’s useful for us to see how they work, because whatever statistical software you might use in practice is applying the same logic and math.)</p>
<div id="tbl-unit-normal" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-unit-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: The unit normal table, showing areas to the left, right, and between the mean and a given <span class="math inline">\(z\)</span> score. Scroll to see more values.
</figcaption>
<div aria-describedby="tbl-unit-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="interactive-figure-mount" data-interactive-options="{&quot;distribution&quot;:&quot;normal&quot;,&quot;layout&quot;:&quot;areas&quot;,&quot;z&quot;:{&quot;from&quot;:0,&quot;to&quot;:3,&quot;step&quot;:0.01},&quot;zDigits&quot;:2,&quot;areas&quot;:[&quot;left&quot;,&quot;right&quot;,&quot;mean-to-z&quot;],&quot;tableMaxHeight&quot;:&quot;18rem&quot;,&quot;selected&quot;:false}" data-interactive-factory="makeCriticalValueTable" data-interactive-figure="unitNormalTable">
<div class="interactive-figure-fallback">
Unit normal table showing areas to the left, right, and between the mean and z.
</div>
</div>
</div>
</figure>
</div>
<p>So for a <span class="math inline">\(z\)</span> score of zero, it’s exactly half and half; 50 percent of the distribution lies on either side of zero, because zero is the mean and the distribution is symmetrical. In other words, under a normal model there is a 50 percent chance of observing a score greater than the mean and a 50 percent chance of observing a score lower than the mean.</p>
<p>If we take a <span class="math inline">\(z\)</span> score of 1, we look for that row in the table. The area to the left of <span class="math inline">\(z=1\)</span> is about .84, so roughly 84 percent of the distribution lies below it. In percentile language, a score with <span class="math inline">\(z=1\)</span> is at about the 84th percentile. The area to the right is just under .16, and the area between the mean (where <span class="math inline">\(z=0\)</span>) and <span class="math inline">\(z=1\)</span> is .3413, just like we saw before. How about a <span class="math inline">\(z\)</span> score of negative one? Standard normal tables don’t always list negative <span class="math inline">\(z\)</span> scores, because the symmetry of the distribution means the relevant areas are the same as for a positive <span class="math inline">\(z\)</span> score on the opposite side of the mean. Only the direction flips: the smaller area (0.1587) is to the left of <span class="math inline">\(z = -1\)</span> and the larger area (0.8413) is to its right.</p>
</section>
<section id="finding-the-area-you-need" class="level3">
<h3 data-anchor-id="finding-the-area-you-need">Finding the Area You Need</h3>
<p>Start with the event, then identify its region on the curve, and only then choose a table entry. For example, suppose scores follow a normal distribution with <span class="math inline">\(\mu=100\)</span> and <span class="math inline">\(\sigma=15\)</span>. A score of 115 has <span class="math inline">\(z=(115-100)/15=1\)</span>; a score of 130 has <span class="math inline">\(z=2\)</span>.</p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Question</th>
<th style="text-align: left;">Standardized event</th>
<th style="text-align: left;">Area from the table</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Below 115?</td>
<td style="text-align: left;"><span class="math inline">\(P(Z&lt;1)\)</span></td>
<td style="text-align: left;">Left of 1: <span class="math inline">\(.8413\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Above 115?</td>
<td style="text-align: left;"><span class="math inline">\(P(Z&gt;1)\)</span></td>
<td style="text-align: left;">Right of 1: <span class="math inline">\(1-.8413=.1587\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Between 115 and 130?</td>
<td style="text-align: left;"><span class="math inline">\(P(1&lt;Z&lt;2)\)</span></td>
<td style="text-align: left;">Left of 2 minus left of 1: <span class="math inline">\(.9772-.8413=.1359\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Between 85 and 115?</td>
<td style="text-align: left;"><span class="math inline">\(P(-1&lt;Z&lt;1)\)</span></td>
<td style="text-align: left;">Twice the mean-to-1 area: <span class="math inline">\(2(.3413)=.6826\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Subtracting the two left-hand areas in the third row removes all the scores below 115, leaving only the region between 115 and 130. In the last row, symmetry gives us equal areas on the two sides of the mean. Each calculation is a way of collecting exactly the region named in the question.</p>
<section class="quiz callout callout-style-default callout-note callout-titled" data-quiz-id="06_probability_distribution" aria-label="Distribution Probabilities"><div class="callout-header d-flex align-content-center"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-caption-container flex-fill"><p>Distribution Probabilities</p></div><span class="quiz-progress" aria-label="0 of 3 questions answered" hidden=""><i class="bi bi-check-circle-fill" aria-hidden="true" hidden=""></i><span data-quiz-progress-label="">0 of 3</span></span></div><div class="callout-body-container callout-body"><article class="quiz-question" data-question-id="z_one_left_area"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">1</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>For a standard normal distribution, what proportion of scores falls
below <span class="math inline">\(z = 1\)</span>?</p></div></div><div class="quiz-control"><fieldset class="quiz-options"><legend class="visually-hidden">Response options</legend><div class="quiz-choice"><input type="radio" name="06_probability_distribution-z_one_left_area" id="06_probability_distribution-z_one_left_area-option-1" value="0" aria-labelledby="06_probability_distribution-z_one_left_area-option-1-text"><div class="quiz-choice-text" id="06_probability_distribution-z_one_left_area-option-1-text"><p>About .16</p></div></div><div class="quiz-choice"><input type="radio" name="06_probability_distribution-z_one_left_area" id="06_probability_distribution-z_one_left_area-option-2" value="1" aria-labelledby="06_probability_distribution-z_one_left_area-option-2-text"><div class="quiz-choice-text" id="06_probability_distribution-z_one_left_area-option-2-text"><p>About .34</p></div></div><div class="quiz-choice"><input type="radio" name="06_probability_distribution-z_one_left_area" id="06_probability_distribution-z_one_left_area-option-3" value="2" aria-labelledby="06_probability_distribution-z_one_left_area-option-3-text"><div class="quiz-choice-text" id="06_probability_distribution-z_one_left_area-option-3-text"><p>About .84</p></div></div><div class="quiz-choice"><input type="radio" name="06_probability_distribution-z_one_left_area" id="06_probability_distribution-z_one_left_area-option-4" value="3" aria-labelledby="06_probability_distribution-z_one_left_area-option-4-text"><div class="quiz-choice-text" id="06_probability_distribution-z_one_left_area-option-4-text"><p>About .98</p></div></div></fieldset></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>About .84</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>A z-score of 1 leaves about 84% of the distribution below it.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="between_z_values"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">2</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>The area to the left of <span class="math inline">\(z=.5\)</span> is
.6915, and the area to the left of <span class="math inline">\(z=1.5\)</span> is .9332. What is <span class="math inline">\(P(.5&lt;Z&lt;1.5)\)</span>?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>0.2417</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>Subtract the smaller left-hand area from the larger: .9332 - .6915 =
.2417. That leaves only the region between the two scores.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article><article class="quiz-question" data-question-id="negative_tail"><div class="quiz-question-header"><span class="quiz-qbadge" aria-hidden="true"><span class="quiz-qbadge-number">3</span><i class="bi bi-check"></i></span><div class="quiz-prompt"><p>The area to the right of <span class="math inline">\(z=1.5\)</span>
is .0668. What is <span class="math inline">\(P(Z &lt;
-1.5)\)</span>?</p></div></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>6.68e-2</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>Symmetry gives the same area in the corresponding left tail.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article></div><script type="application/json" class="quiz-data" data-quiz-id="06_probability_distribution">{"title":"Distribution Probabilities","questions":[{"type":"multiple-choice","options":[{"text":"About .16","textHtml":"\u003cp\u003eAbout .16\u003c/p\u003e"},{"text":"About .34","textHtml":"\u003cp\u003eAbout .34\u003c/p\u003e"},{"text":"About .84","textHtml":"\u003cp\u003eAbout .84\u003c/p\u003e","correct":true},{"text":"About .98","textHtml":"\u003cp\u003eAbout .98\u003c/p\u003e"}],"prompt":"For a standard normal distribution, what proportion of scores falls below z = 1?","promptHtml":"\u003cp\u003eFor a standard normal distribution, what proportion of scores falls\nbelow \u003cspan class=\"math inline\"\u003e\\(z = 1\\)\u003c/span\u003e?\u003c/p\u003e","explanation":"A z-score of 1 leaves about 84% of the distribution below it.","explanationHtml":"\u003cp\u003eA z-score of 1 leaves about 84% of the distribution below it.\u003c/p\u003e","id":"z_one_left_area","answerHtml":""},{"answer":"0.2417","tolerance":"1.0e-4","prompt":"The area to the left of z=.5 is .6915, and the area to the left of z=1.5 is .9332. What is P(.5\u003cZ\u003c1.5)?","promptHtml":"\u003cp\u003eThe area to the left of \u003cspan class=\"math inline\"\u003e\\(z=.5\\)\u003c/span\u003e is\n.6915, and the area to the left of \u003cspan\nclass=\"math inline\"\u003e\\(z=1.5\\)\u003c/span\u003e is .9332. What is \u003cspan\nclass=\"math inline\"\u003e\\(P(.5\u0026lt;Z\u0026lt;1.5)\\)\u003c/span\u003e?\u003c/p\u003e","explanationHtml":"\u003cp\u003eSubtract the smaller left-hand area from the larger: .9332 - .6915 =\n.2417. That leaves only the region between the two scores.\u003c/p\u003e","explanation":"Subtract the smaller left-hand area from the larger: .9332 - .6915 = .2417. That leaves only the region between the two scores.","type":"numeric","id":"between_z_values","answerHtml":"\u003cp\u003e0.2417\u003c/p\u003e"},{"answer":"6.68e-2","tolerance":"1.0e-4","prompt":"The area to the right of z=1.5 is .0668. What is P(Z \u003c -1.5)?","promptHtml":"\u003cp\u003eThe area to the right of \u003cspan class=\"math inline\"\u003e\\(z=1.5\\)\u003c/span\u003e\nis .0668. What is \u003cspan class=\"math inline\"\u003e\\(P(Z \u0026lt;\n-1.5)\\)\u003c/span\u003e?\u003c/p\u003e","explanationHtml":"\u003cp\u003eSymmetry gives the same area in the corresponding left tail.\u003c/p\u003e","explanation":"Symmetry gives the same area in the corresponding left tail.","type":"numeric","id":"negative_tail","answerHtml":"\u003cp\u003e6.68e-2\u003c/p\u003e"}],"id":"06_probability_distribution","titleHtml":"\u003cp\u003eDistribution Probabilities\u003c/p\u003e"}</script></section>
</section>
</section>
<section id="applying-probability-spider-man" class="level2">
<h2 data-anchor-id="applying-probability-spider-man">Applying Probability: Spider-Man</h2>
<p>To finish up, let’s turn back to our silly Spider-Man reaction time test from the previous chapter. We found that Peter Parker’s <span class="math inline">\(z\)</span> score was <span class="math inline">\(-2.5\)</span>, and we said that that seemed pretty extreme. But now we’re equipped to determine probabilities under a normal model, and we can be more precise.</p>
<p>What are the chances that if we randomly selected someone from our reference population of ordinary, unbitten people they would have a reaction time as quick as Peter’s or quicker?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> As you can see on the normal curve, reaction times that fast make up a very small lower-tail region of the distribution.</p>
<div id="fig-spiderman-z-score" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-spiderman-z-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.6: A normal distribution curve with a vertical line at <span class="math inline">\(z = -2.5\)</span>, representing the position of Peter Parker’s reaction time within the standardized population distribution.
</figcaption>
<div aria-describedby="fig-spiderman-z-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="interactive-figure-mount" data-interactive-options="{&quot;distribution&quot;:&quot;normal&quot;,&quot;xDomain&quot;:[-4,4],&quot;xTicks&quot;:9,&quot;style&quot;:&quot;minimal&quot;,&quot;xAxis&quot;:true,&quot;shade&quot;:{&quot;to&quot;:-2.5},&quot;markers&quot;:{&quot;at&quot;:-2.5,&quot;label&quot;:&quot;z = −2.5&quot;,&quot;height&quot;:0.45,&quot;color&quot;:&quot;var(--sfs-accent, #2c7fb8)&quot;},&quot;animate&quot;:true,&quot;labels&quot;:{&quot;x&quot;:&quot;z-score&quot;}}" data-interactive-factory="makeDistributionGraph" data-interactive-figure="spideyProbabilityCurve">
<div class="interactive-figure-fallback">
Standard normal curve with a vertical line at z equals negative 2.5 and the small region below it shaded.
</div>
</div>
</div>
</figure>
</div>
<p>Our table lists positive <span class="math inline">\(z\)</span> scores, so look up <span class="math inline">\(2.5\)</span> and read the area to its right. By symmetry, this is also the area to the left of <span class="math inline">\(-2.5\)</span>: about .0062, or 0.62%:</p>
<p><span class="math display">\[P(Z \le -2.5) \approx .0062\]</span></p>
<p>In other words, if we tested a random individual from this population, there’s less than a 1% chance that they would be as quick as or quicker than Peter Parker. That is evidence against the idea that Peter is just an ordinary member of the reference population. It isn’t proof: rare scores do sometimes happen, and this probability is not itself the probability that the spider bite changed him. But it gives us a more precise reason to begin suspecting that something unusual is going on. In <a href="./08-hypothesis-testing.html">Chapter 8</a>, we’ll develop that logic into a formal hypothesis test.</p>
<section class="quiz callout callout-style-default callout-note callout-titled" data-quiz-id="06_probability_z_scores_table" aria-label="Find the Relevant Probabilities"><div class="callout-header d-flex align-content-center"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-caption-container flex-fill"><p>Find the Relevant Probabilities</p></div></div><div class="callout-body-container callout-body"><article class="quiz-question" data-question-id="peter_tail"><div class="quiz-prompt"><p>For Peter Parker’s reaction time, <span class="math inline">\(z =
-2.5\)</span>. What is the approximate lower- tail probability?</p></div><div class="quiz-control"><div class="quiz-input-shell quiz-input-shell-numeric"><input type="text" inputmode="decimal" autocomplete="off" placeholder="Enter a number" aria-label="Numeric response"><span class="quiz-input-status" aria-hidden="true"></span></div></div><div class="quiz-actions" hidden=""><button type="button" data-quiz-action="check"></button><button type="button" class="quiz-secondary" data-quiz-action="hint" hidden="">Show hint</button><button type="button" class="quiz-secondary" data-quiz-action="reveal" hidden="">Show answer</button><button type="button" class="quiz-secondary" data-quiz-action="diagnostics" hidden="">Check your work</button><button type="button" class="quiz-clear" data-quiz-action="clear" aria-label="Clear saved response" hidden="">Clear</button></div><div class="quiz-feedback" aria-live="polite" hidden=""><strong data-quiz-feedback-label=""></strong></div><div class="quiz-hints-panel" hidden=""></div><div class="quiz-explanation-panel" hidden=""><div class="quiz-model-answer"><strong>Answer</strong><p>6.2e-3</p></div><div class="quiz-explanation-rendered"><strong>Explanation</strong><p>The area below z = -2.5 is about .0062, or 0.62%.</p></div></div><div class="quiz-diagnostics" hidden=""></div></article></div><script type="application/json" class="quiz-data" data-quiz-id="06_probability_z_scores_table">{"title":"Find the Relevant Probabilities","questions":[{"answer":"6.2e-3","tolerance":"5.0e-4","prompt":"For Peter Parker’s reaction time, z = -2.5. What is the approximate lower- tail probability?","promptHtml":"\u003cp\u003eFor Peter Parker’s reaction time, \u003cspan class=\"math inline\"\u003e\\(z =\n-2.5\\)\u003c/span\u003e. What is the approximate lower- tail probability?\u003c/p\u003e","explanationHtml":"\u003cp\u003eThe area below z = -2.5 is about .0062, or 0.62%.\u003c/p\u003e","explanation":"The area below z = -2.5 is about .0062, or 0.62%.","type":"numeric","id":"peter_tail","answerHtml":"\u003cp\u003e6.2e-3\u003c/p\u003e"}],"id":"06_probability_z_scores_table","titleHtml":"\u003cp\u003eFind the Relevant Probabilities\u003c/p\u003e"}</script></section>
<section id="a-note-on-normality" class="level3">
<h3 data-anchor-id="a-note-on-normality">A Note on Normality</h3>
<p>One last thing to note: these particular probabilities come from a normal model. If the population distribution has a different shape — say, if it’s strongly skewed or bimodal — the normal curve’s areas might not describe it well. So in practice we don’t simply assume that every distribution is normal, and we can’t conclusively “verify” normality from a finite set of observations. We assess whether a normal model is reasonable enough for what we’re trying to do.</p>
<p>The objects have changed over the course of the chapter — dice outcomes, marbles, blocks in a histogram, areas under a curve — but the underlying question has stayed the same. What are the possible results, and how much of that possibility belongs to the event we care about? In the next chapter, we’ll ask that question about sample means. And we’ll see an important complication: under certain conditions, a distribution of sample means can be approximately normal even when the population of individual scores is not.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-bernoulli2006conjecturing" class="csl-entry" role="listitem">
Bernoulli, J. (2006). <em>The art of conjecturing, together with <span>“letter to a friend on sets in court tennis”</span></em> (E. D. Sylla, Tran.). Johns Hopkins University Press.
</div>
<div id="ref-galileo1898dadi" class="csl-entry" role="listitem">
Galilei, G. (1898). Sopra le scoperte dei dadi. In <em>Le opere di galileo galilei</em> (Vol. 8, pp. 591–594). Barbera. <a href="https://web.universiteitleiden.nl/fsw/verduin/stathist/galileo.htm">https://web.universiteitleiden.nl/fsw/verduin/stathist/galileo.htm</a>
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>No less a genuis than Galileo was recruited, possibly by a gambling duke looking to secure a statistical advantage, to investigate a version of this puzzle <span class="citation" data-cites="galileo1898dadi">(<a href="references.html#ref-galileo1898dadi" role="doc-biblioref">Galilei, 1898</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The real game also has a bunch of other considerations that I skipped over here: what resources those tiles produce, what you’re trying to build, what the other players have already taken, and what you might be able to trade.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Notice the question isn’t about Parker himself: he has already recorded his score, so it doesn’t make sense to ask for the probability that <em>he</em> got it.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<!-- Cloudflare Web Analytics --><script type="module" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;50a01b5aaab349e68994c2806a9211de&quot;}"></script><!-- End Cloudflare Web Analytics -->
<script src="resources/js/quiz.js"></script>
<script src="resources/js/anchor-navigation.js"></script>
<script src="resources/js/sidebar-toc.js"></script>
<script>window.interactiveRuntime && window.interactiveRuntime.init();</script>
<script src="resources/js/mobile-nav.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/statisticsfromscratch\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./05-z-scores.html" class="pagination-link" aria-label="$z$-Scores">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><span class="math inline">\(z\)</span>-Scores</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-sampling.html" class="pagination-link" aria-label="Sampling">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>