project:
  type: book
  output-dir: docs

resources:
  - resources/

book:
  bread-crumbs: false
  navbar:
    background: none
    pinned: true
    title: 'Statistics From Scratch <span class="bc-navbar-author">by Rob Brotherton</span>'
  title: "Statistics From Scratch"
  subtitle: "An Introduction for the Social Sciences"
  author: "Rob Brotherton"
  description: "An interactive introduction to statistics for students in the social sciences."
  site-url: "https://statisticsfromscratch.com"
  favicon: resources/icons/favicon.svg
  open-graph: true
  twitter-card: true
  chapters:
    - index.qmd
    - 01-variables.qmd
    - 02-frequency-distributions.qmd
    - 03-central-tendency.qmd
    - 04-variability.qmd
    - 05-z-scores.qmd
    - 06-probability.qmd
    - 07-sampling.qmd
    - 08-hypothesis-testing.qmd
    - 09-statistical-power.qmd
    - 10-confidence-intervals.qmd
    - 11-t-test.qmd
    - 12-independent-samples-t-test.qmd
    - 13-related-samples-t-test.qmd
    - 14-anova.qmd
    - 15-related-samples-anova.qmd
    - 16-factorial-anova.qmd
    - 17-correlation.qmd
    - 18-regression.qmd
    - references.qmd
    

bibliography: references.bib
csl: https://www.zotero.org/styles/apa

execute:
  echo: false
  freeze: auto

fig-cap-location: top

filters:
  - filters/responsive-tables.lua
  - filters/interactive-scripts.lua
  - path: filters/quiz-yaml.lua
    at: post-quarto

crossref:
  custom:
    - kind: float
      key: quiz
      reference-prefix: Quiz
    - kind: float
      key: act
      reference-prefix: Activity

language:
  callout-tip-title: Activity
  callout-note-title: Quiz

format:
  html:
    lightbox: true
    page-layout: full
    body-classes: fullcontent
    grid:
      sidebar-width: 300px
    anchor-sections: false
    number-sections: true
    number-depth: 1
    crossrefs-hover: false
    theme:
      light: [flatly, resources/css/theme.scss]
      dark: [darkly, resources/css/theme.scss]
    respect-user-color-scheme: true
    css:
      - resources/css/site-theme.css
      - resources/css/quiz.css
    include-in-header:
      - resources/includes/interactive-runtime-head.html
    include-after-body:
      - resources/includes/quiz.html
      - resources/includes/sidebar-toc.html
      - resources/includes/interactive-runtime.html
      - resources/includes/mobile-nav.html

link-external-newwindow: true
